### ISSUE TITLE
Can't run example files

### ISSUE THREAD

**Issue by jcollard** [rose-lang/rose#1]
I can't figure out how to run this code:

```
data Bool = True | False

data State =
  | 😀
  | 😉
  | 😈

let main =
  match st with
    case 😈 as False
    otherwise True

let st = 😈
```

Looking forward to seeing more :+1:

**Comment by aatxe** [comment]
There was a Scala interpreter a while ago that could actually run all the examples, and then after that a false-start on an LLVM compiler (which could not). They're both in the git history (maybe I should add a git tag, at least for the Scala interpreter). My intentions have changed a bit since I first wrote that stuff though. The plan right now is to write a semantics in Redex and a nanopass compiler to wasm. Until some of the semantics come up (which I'm hacking on now, but it's also 3 am here), the documentation in the readme and the examples for some flavor are all that's here.

**Comment by jcollard** [comment]
Cool. At a glance, it looked like the project was only a few hours old. Also, I'm assuming some semi-major revisions will be coming (or at least planned) in the future.

Thanks for the quick reply!
